// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzK01gZwRbxYDayI62xcN4RGxoyOC0Nng',
    appId: '1:162155995695:web:f5c262fad437cbe8979cda',
    messagingSenderId: '162155995695',
    projectId: 'second-flutter-withfirebase',
    authDomain: 'second-flutter-withfirebase.firebaseapp.com',
    storageBucket: 'second-flutter-withfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbIZqphzOA2OwC8qxLwCDfCfVtgZ63lI8',
    appId: '1:162155995695:android:e607171452df8840979cda',
    messagingSenderId: '162155995695',
    projectId: 'second-flutter-withfirebase',
    storageBucket: 'second-flutter-withfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd6Mqjve3cDXLasjQPwMkscvFLFcUsr9c',
    appId: '1:162155995695:ios:f7fbfb5cd1134653979cda',
    messagingSenderId: '162155995695',
    projectId: 'second-flutter-withfirebase',
    storageBucket: 'second-flutter-withfirebase.firebasestorage.app',
    iosBundleId: 'com.example.conetFlutterWithfirebase',
  );
}
